### ISSUE TITLE
minio_storage module not found

### ISSUE THREAD

**Issue by ebrahimebrahim** [girder/otm-server#23]
This is an error that I get after following the setup instructions in the readme and then running `docker-compose up`:

```txt
celery_1    | Traceback (most recent call last):
celery_1    |   File "/usr/local/bin/celery", line 8, in <module>
celery_1    |     sys.exit(main())
celery_1    |   File "/usr/local/lib/python3.8/dist-packages/celery/__main__.py", line 15, in main
celery_1    |     sys.exit(_main())
celery_1    |   File "/usr/local/lib/python3.8/dist-packages/celery/bin/celery.py", line 213, in main
celery_1    |     return celery(auto_envvar_prefix="CELERY")
celery_1    |   File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1128, in __call__
celery_1    |     return self.main(*args, **kwargs)
celery_1    |   File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1053, in main
celery_1    |     rv = self.invoke(ctx)
celery_1    |   File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1659, in invoke
celery_1    |     return _process_result(sub_ctx.command.invoke(sub_ctx))
celery_1    |   File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1395, in invoke
celery_1    |     return ctx.invoke(self.callback, **ctx.params)
celery_1    |   File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 754, in invoke
celery_1    |     return __callback(*args, **kwargs)
celery_1    |   File "/usr/local/lib/python3.8/dist-packages/click/decorators.py", line 26, in new_func
celery_1    |     return f(get_current_context(), *args, **kwargs)
celery_1    |   File "/usr/local/lib/python3.8/dist-packages/celery/bin/base.py", line 134, in caller
celery_1    |     return f(ctx, *args, **kwargs)
celery_1    |   File "/usr/local/lib/python3.8/dist-packages/celery/bin/worker.py", line 343, in worker
celery_1    |     worker = app.Worker(
celery_1    |   File "/usr/local/lib/python3.8/dist-packages/celery/worker/worker.py", line 94, in __init__
celery_1    |     self.app.loader.init_worker()
celery_1    |   File "/usr/local/lib/python3.8/dist-packages/celery/loaders/base.py", line 111, in init_worker
celery_1    |     self.import_default_modules()
celery_1    |   File "/usr/local/lib/python3.8/dist-packages/celery/loaders/base.py", line 105, in import_default_modules
celery_1    |     raise response
celery_1    |   File "/usr/local/lib/python3.8/dist-packages/celery/utils/dispatch/signal.py", line 276, in send
celery_1    |     response = receiver(signal=self, sender=sender, **named)
celery_1    |   File "/usr/local/lib/python3.8/dist-packages/celery/fixups/django.py", line 82, in on_import_modules
celery_1    |     self.worker_fixup.validate_models()
celery_1    |   File "/usr/local/lib/python3.8/dist-packages/celery/fixups/django.py", line 121, in validate_models
celery_1    |     run_checks()
celery_1    |   File "/usr/local/lib/python3.8/dist-packages/django/core/checks/registry.py", line 88, in run_checks
celery_1    |     new_errors = check(app_configs=app_configs, databases=databases)
celery_1    |   File "/usr/local/lib/python3.8/dist-packages/s3_file_field/checks.py", line 18, in test_bucket_access
celery_1    |     if not MultipartManager.supported_storage(storage):
celery_1    |   File "/usr/local/lib/python3.8/dist-packages/s3_file_field/_multipart.py", line 144, in supported_storage
celery_1    |     cls.from_storage(storage)
celery_1    |   File "/usr/local/lib/python3.8/dist-packages/s3_file_field/_multipart.py", line 124, in from_storage
celery_1    |     if isinstance(storage, S3Boto3Storage):
celery_1    |   File "/usr/local/lib/python3.8/dist-packages/django/utils/functional.py", line 258, in inner
celery_1    |     self._setup()
celery_1    |   File "/usr/local/lib/python3.8/dist-packages/django/core/files/storage.py", line 413, in _setup
celery_1    |     self._wrapped = get_storage_class()()
celery_1    |   File "/usr/local/lib/python3.8/dist-packages/django/core/files/storage.py", line 408, in get_storage_class
celery_1    |     return import_string(import_path or settings.DEFAULT_FILE_STORAGE)
celery_1    |   File "/usr/local/lib/python3.8/dist-packages/django/utils/module_loading.py", line 30, in import_string
celery_1    |     return cached_import(module_path, class_name)
celery_1    |   File "/usr/local/lib/python3.8/dist-packages/django/utils/module_loading.py", line 15, in cached_import
celery_1    |     import_module(module_path)
celery_1    |   File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
celery_1    |     return _bootstrap._gcd_import(name[level:], package, level)
celery_1    |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
celery_1    |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
celery_1    |   File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
celery_1    |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
celery_1    |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
celery_1    |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
celery_1    |   File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
celery_1    | ModuleNotFoundError: No module named 'minio_storage'
```

**Comment by banesullivan** [comment]
I am able to reproduce this and it's very odd as the `dev` extra for this project specifies S3FF to install the `minio` dependencies in

https://github.com/girder/otm-server/blob/3f6fdc77d4bd25f88b743cf6ef9e650903d29f63/setup.py#L65

Which is specified when installing in the celery docker image:

https://github.com/girder/otm-server/blob/3f6fdc77d4bd25f88b743cf6ef9e650903d29f63/dev/celery.Dockerfile#L24

and this is indeed the dockerfile for the celery service:

https://github.com/girder/otm-server/blob/3f6fdc77d4bd25f88b743cf6ef9e650903d29f63/docker-compose.override.yml#L23

To prove the dependencies aren't right, I can exec into the `celery` service and run `pip list` and see that `djanngo-minio-stroage` is indeed not installed:

```
...
Django                        3.2.12
django-admin-display          1.3.0
django-allauth                0.49.0
django-auth-style             0.8.1
django-cleanup                6.0.0
django-click                  2.3.0
django-composed-configuration 0.20.0
django-configurations         2.3.2
django-cors-headers           3.11.0
django-debug-toolbar          3.2.4
django-extensions             3.1.5
django-filter                 21.1
django-girder-utils           0.11.0
django-oauth-toolkit          1.7.0
django-s3-file-field          0.3.0
django-storages               1.12.3
djangorestframework           3.13.1
drf-yasg                      1.20.0
```

I will continue to investigate why the dependencies are right in the celery service

**Comment by banesullivan** [comment]
This appears to be an issue related to pip which is filed here: https://github.com/pypa/pip/issues/10891 for versions 22+ but I'm seeing it here regardless of pip version.

I noticed the base `rocker/shiny:4.1.0` image in the `celery` image and changed to using `pip3` which is installed here:

https://github.com/girder/otm-server/blob/3f6fdc77d4bd25f88b743cf6ef9e650903d29f63/dev/celery.Dockerfile#L10

change here:

https://github.com/girder/otm-server/blob/3f6fdc77d4bd25f88b743cf6ef9e650903d29f63/dev/celery.Dockerfile#L24

----

Even with that, I can do the following in that image and still have an issue:


```bash
root@5a00ed433646:/opt/django-project# pip3 install -e .[dev]
...
root@5a00ed433646:/opt/django-project# python3
Python 3.8.10 (default, Nov 26 2021, 20:14:08)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import minio_storage
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'minio_storage'
>>> exit()
```

Which is not expected as `pip3 install -e .[dev]` should install the dev dependencies! So this is either an issue with `pip` itself, the extra dependencies handling in `django-s3-file-field`, or something wack going on with the `rocker/shiny:4.1.0` base image and any Python shipped with it.

cc @brianhelba, @zachmullen

**Comment by banesullivan** [comment]
Related to https://github.com/girder/cookiecutter-girder-4/pull/132 with issues with pip's package resolver

I will open a PR soon that implements a workaround for this
