### ISSUE TITLE
Fix import error in preprocessing task

### ISSUE THREAD

**Issue by ebrahimebrahim** [girder/otm-server#76]
Preprocessing does not run, and I get the following from otm-server

```txt
django_1    | [16:15:42] WARNING  Bad Request: /api/v1/datasets/2/preprocess        log.py:224
django_1    |            WARNING  "POST /api/v1/datasets/2/preprocess          basehttp.py:161
django_1    |                     HTTP/1.1" 400 36        
```

**Comment by AlmightyYakob** [comment]
This is likely due to you having previously run preprocessing, and then it failing in the middle. So the preprocessing status of the dataset is still set to `Running`.

There are some steps we can take to fix this, I can look into them. I'll rename this issue to better reflect the root cause.

**Comment by ebrahimebrahim** [comment]
The error I showed seems to be as you're saying: failed task prevents further attempts.
I flushed my database and did a clean start to be able to run the task again, and this time I saw from the first run *why* it failed:

```txt
celery_1    | [2022-08-04 14:58:21,562: INFO/MainProcess] Task optimal_transport_morphometry.core.tasks.preprocess_images[c8da8b35-4b3a-47ad-a9fd-5328202e6128] received
celery_1    | [2022-08-04 14:58:21,565: ERROR/ForkPoolWorker-1] Task optimal_transport_morphometry.core.tasks.preprocess_images[c8da8b35-4b3a-47ad-a9fd-5328202e6128] raised unexpected: ModuleNotFoundError("No module named 'ants'")
celery_1    | Traceback (most recent call last):
celery_1    |   File "/usr/local/lib/python3.8/dist-packages/celery/app/trace.py", line 451, in trace_task
celery_1    |     R = retval = fun(*args, **kwargs)
celery_1    |   File "/usr/local/lib/python3.8/dist-packages/celery/app/trace.py", line 734, in __protected_call__
celery_1    |     return self.run(*args, **kwargs)
celery_1    |   File "/opt/django-project/optimal_transport_morphometry/core/tasks.py", line 18, in preprocess_images
celery_1    |     import ants
celery_1    | ModuleNotFoundError: No module named 'ants'
```

**Comment by AlmightyYakob** [comment]
I see the issue. I'll make a PR to fix it.
